package com.zixuan.kg64;

import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.os.*;import android.text.*;import android.view.*;import android.widget.*;import java.time.*;import java.time.temporal.*;import java.util.*;

public class MainActivityV6 extends Activity{
 static final int INK=Color.rgb(23,25,22),CREAM=Color.rgb(245,243,234),LIME=Color.rgb(216,255,82),MUTED=Color.rgb(105,108,100),LINE=Color.rgb(232,230,220);static final float TARGET=64f;final LocalDate GOAL=LocalDate.of(2026,10,1);
 SharedPreferences p;LinearLayout root,sleepEditor;TextView gapV,daysV,weightV,liquidV,sleepDur,intakeV,planV,actualV,waterV,fastingV;NumberPicker sh,sm,wh,wm;EditText[][] meal=new EditText[4][4];EditText ball,walk,run;CheckBox coffee;Button sleepConfirm;boolean rendering;
 String[] mealKeys={"breakfast","lunch","dinner","snack"},mealNames={"早餐","午餐","晚餐","加餐"};
 public void onCreate(Bundle b){super.onCreate(b);p=getSharedPreferences("kg64_data",MODE_PRIVATE);getWindow().setStatusBarColor(CREAM);getWindow().setNavigationBarColor(INK);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR);render();}
 void render(){rendering=true;ScrollView sc=new ScrollView(this);sc.setFillViewport(true);sc.setBackgroundColor(CREAM);sc.setClipToPadding(false);sc.setOnApplyWindowInsetsListener((v,i)->{v.setPadding(0,i.getSystemWindowInsetTop(),0,i.getSystemWindowInsetBottom());return i;});root=col();root.setPadding(dp(18),dp(16),dp(18),dp(40));sc.addView(root);
 TextView brand=t("64KG / DAILY",13,true,INK);brand.setLetterSpacing(.14f);root.addView(brand);root.addView(sp(7));root.addView(t("睡好 → 吃清楚 → 动起来",25,true,INK));root.addView(sp(18));
 LinearLayout hero=row();LinearLayout g=heroStat("距离 64 KG","--","kg");gapV=(TextView)((LinearLayout)g.getChildAt(1)).getChildAt(0);hero.addView(g,new LinearLayout.LayoutParams(0,dp(150),1));View div=new View(this);div.setBackgroundColor(Color.rgb(65,67,61));hero.addView(div,new LinearLayout.LayoutParams(dp(1),dp(92)));LinearLayout d=heroStat("目标倒数","--","天");daysV=(TextView)((LinearLayout)d.getChildAt(1)).getChildAt(0);hero.addView(d,new LinearLayout.LayoutParams(0,dp(150),1));root.addView(card(hero,INK));root.addView(sp(12));LinearLayout mini=row();weightV=mini(mini,"当前体重","-- kg");mini(mini,"目标日期","10 / 01");liquidV=mini(mini,"本周液断","剩 2 次");root.addView(card(mini,Color.WHITE));
 section("① 睡眠","先设置睡眠；点绿色框确认固定，再点一次即可修改");root.addView(sleepCard());
 section("② 吃饭","填写拳数、进食时间和咖啡；每餐可单独确认");root.addView(t("主食1拳≈180 kcal｜蛋白质1拳≈160 kcal｜蔬菜1拳≈50 kcal｜其他/高油1拳≈220 kcal",12,false,MUTED));root.addView(sp(10));
 root.addView(mealBox(0,"建议：主食0.5–1拳｜蛋白质0.5–1拳｜蔬菜0–1拳｜其他0–0.5拳｜约300–350 kcal"));root.addView(sp(8));root.addView(mealBox(1,"建议：主食1拳｜蛋白质1拳｜蔬菜2拳｜其他0–0.5拳｜约500–550 kcal"));root.addView(sp(8));root.addView(mealBox(2,"建议：主食0.5–1拳｜蛋白质1拳｜蔬菜2拳｜其他0–0.5拳｜约400–450 kcal"));root.addView(sp(8));root.addView(mealBox(3,"建议：总量0.25–0.5拳，优先少油少糖｜约100–150 kcal"));root.addView(sp(10));intakeV=t("今日摄入估算：0 kcal",18,true,INK);intakeV.setPadding(dp(14),dp(13),dp(14),dp(13));intakeV.setBackground(round(LIME));root.addView(intakeV);root.addView(sp(8));fastingV=t("16+8：等待进食时间",13,true,INK);root.addView(fastingV);
 section("③ 喝水","点按钮快速累计，也可以直接输入毫升数");root.addView(waterCard());
 section("④ 运动","根据睡眠 + 今日摄入 + 当前体重动态换算");planV=t("",15,true,INK);planV.setLineSpacing(0,1.35f);root.addView(card(planV,Color.WHITE));root.addView(sp(10));LinearLayout ex=col();ex.addView(t("填写实际完成量",15,true,INK));ex.addView(sp(8));ball=num("打球：分钟");ball.setText(pref("ball_minutes_actual"));watch(ball,"ball_minutes_actual");ex.addView(ball,new LinearLayout.LayoutParams(-1,dp(50)));ex.addView(sp(7));walk=num("快走：步数");walk.setText(pref("walk_steps_actual"));watch(walk,"walk_steps_actual");ex.addView(walk,new LinearLayout.LayoutParams(-1,dp(50)));ex.addView(sp(7));run=dec("跑步：400m操场圈数");run.setText(pref("run_laps_actual"));watch(run,"run_laps_actual");ex.addView(run,new LinearLayout.LayoutParams(-1,dp(50)));ex.addView(sp(8));actualV=t("",13,true,INK);actualV.setLineSpacing(0,1.3f);ex.addView(actualV);Button ec=btn(p.getBoolean(key("exercise_confirmed"),false)?"已确认运动 · 点此修改":"确认今天运动",LIME,INK);ec.setOnClickListener(v->{boolean n=!p.getBoolean(key("exercise_confirmed"),false);p.edit().putBoolean(key("exercise_confirmed"),n).apply();saveDailySnapshot();render();});ex.addView(sp(8));ex.addView(ec,new LinearLayout.LayoutParams(-1,dp(48)));root.addView(card(ex,Color.WHITE));
 section("体重记录","记录后上方视觉中心立即更新");LinearLayout wr=row();EditText wi=dec("输入体重 kg");wr.addView(wi,new LinearLayout.LayoutParams(0,dp(52),1));Button sb=btn("记录",LIME,INK);sb.setOnClickListener(v->saveWeight(wi));LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(dp(92),dp(52));bp.setMargins(dp(10),0,0,0);wr.addView(sb,bp);root.addView(wr);
 section("趋势与健康","日期节点 + 曲线；点击节点查看当天详情");root.addView(trendSection("体重趋势","weight"));root.addView(sp(10));root.addView(trendSection("吃饭稳定率 · 16+8","diet_stability"));root.addView(sp(10));root.addView(trendSection("吃饭健康率 · 饮食结构","diet_health"));root.addView(sp(10));root.addView(trendSection("睡眠稳定率","sleep_stability"));root.addView(sp(10));root.addView(trendSection("睡眠健康率","sleep_health"));root.addView(sp(10));root.addView(trendSection("运动稳定率","exercise_stability"));root.addView(sp(10));root.addView(trendSection("运动健康率","exercise_health"));root.addView(sp(10));root.addView(trendSection("喝水完成率","water"));
 section("液断日","每周最多2次");LinearLayout li=col();li.addView(t(isLiquid()?"今天是液断日":"今天正常饮食",19,true,INK));li.addView(sp(10));Button tg=btn(isLiquid()?"取消今天液断":"设为今天液断",LIME,INK);tg.setOnClickListener(v->toggleLiquid());li.addView(tg,new LinearLayout.LayoutParams(-1,dp(50)));root.addView(card(li,Color.WHITE));setContentView(sc);refresh();rendering=false;updateSleep();updateAll();}
 View sleepCard(){LinearLayout b=col();sleepEditor=col();int a=p.getInt(key("sleep_hour"),0),c=p.getInt(key("sleep_minute"),30),d=p.getInt(key("wake_hour"),8),e=p.getInt(key("wake_minute"),0);sleepEditor.addView(timeRow("睡",a,c,true));View line=new View(this);line.setBackgroundColor(LINE);sleepEditor.addView(line,new LinearLayout.LayoutParams(-1,dp(1)));sleepEditor.addView(timeRow("起",d,e,false));b.addView(sleepEditor);sleepDur=t("共 -- 小时 -- 分钟",17,true,INK);sleepDur.setGravity(Gravity.CENTER);sleepDur.setPadding(dp(10),dp(12),dp(10),dp(12));sleepDur.setBackground(round(LIME));sleepDur.setOnClickListener(v->toggleSleepLock());b.addView(sp(8));b.addView(sleepDur);sleepConfirm=btn("",Color.WHITE,INK);sleepConfirm.setVisibility(View.GONE);b.addView(sleepConfirm,new LinearLayout.LayoutParams(-1,1));boolean locked=p.getBoolean(key("sleep_confirmed"),false);setSleepEnabled(!locked);NumberPicker.OnValueChangeListener li=(x,o,n)->{if(rendering)return;p.edit().putInt(key("sleep_hour"),sh.getValue()).putInt(key("sleep_minute"),sm.getValue()).putInt(key("wake_hour"),wh.getValue()).putInt(key("wake_minute"),wm.getValue()).apply();updateSleep();updateAll();};sh.setOnValueChangedListener(li);sm.setOnValueChangedListener(li);wh.setOnValueChangedListener(li);wm.setOnValueChangedListener(li);return card(b,Color.WHITE);}
 void toggleSleepLock(){boolean locked=p.getBoolean(key("sleep_confirmed"),false);if(!locked){p.edit().putBoolean(key("sleep_confirmed"),true).apply();setSleepEnabled(false);saveDailySnapshot();toast("睡眠已确认，点绿色框可再次修改");}else{p.edit().putBoolean(key("sleep_confirmed"),false).apply();setSleepEnabled(true);toast("已解锁，可以重新调整睡眠时间");}updateSleep();}
 void setSleepEnabled(boolean enabled){if(sh!=null){sh.setEnabled(enabled);sm.setEnabled(enabled);wh.setEnabled(enabled);wm.setEnabled(enabled);sleepEditor.setAlpha(enabled?1f:.48f);}}
 LinearLayout timeRow(String l,int h,int m,boolean sleep){LinearLayout r=row();r.addView(t(l,20,true,INK),new LinearLayout.LayoutParams(dp(48),-2));NumberPicker hp=picker(0,23,h),mp=picker(0,59,m);if(sleep){sh=hp;sm=mp;}else{wh=hp;wm=mp;}r.addView(hp,new LinearLayout.LayoutParams(0,dp(112),1));TextView colon=t(":",30,true,INK);colon.setGravity(Gravity.CENTER);r.addView(colon,new LinearLayout.LayoutParams(dp(28),dp(112)));r.addView(mp,new LinearLayout.LayoutParams(0,dp(112),1));return r;}
 NumberPicker picker(int min,int max,int v){NumberPicker n=new NumberPicker(this);n.setMinValue(min);n.setMaxValue(max);n.setValue(Math.max(min,Math.min(max,v)));n.setWrapSelectorWheel(true);n.setDescendantFocusability(NumberPicker.FOCUS_BLOCK_DESCENDANTS);n.setFormatter(x->String.format(Locale.CHINA,"%02d",x));return n;}
 View mealBox(int ix,String rec){String k=mealKeys[ix];LinearLayout b=col();LinearLayout head=row();head.addView(t(mealNames[ix],18,true,INK),new LinearLayout.LayoutParams(0,-2,1));TextView total=t("本餐 0 kcal",14,true,INK);head.addView(total);b.addView(head);b.addView(sp(6));TextView rv=t(rec,12,true,INK);rv.setPadding(dp(10),dp(8),dp(10),dp(8));rv.setBackground(round(LIME));b.addView(rv);b.addView(sp(9));String[] names={"主食：实际几拳（1拳≈180 kcal）","蛋白质：实际几拳（1拳≈160 kcal）","蔬菜：实际几拳（1拳≈50 kcal）","其他/高油：实际几拳（1拳≈220 kcal）"},ks={"_staple","_protein","_veg","_other"};for(int j=0;j<4;j++){EditText e=dec(names[j]);e.setText(pref(k+ks[j]));final int mealIndex=ix;e.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int bb,int c){}public void onTextChanged(CharSequence s,int a,int bb,int c){}public void afterTextChanged(Editable s){if(rendering)return;p.edit().putString(key(k+ks[mealIndex==ix?indexOf(e,meal[ix]):0]),s.toString().trim()).apply();total.setText("本餐 "+Math.round(mealKcal(ix))+" kcal");updateAll();}});meal[ix][j]=e;b.addView(e,new LinearLayout.LayoutParams(-1,dp(48)));if(j<3)b.addView(sp(6));}
 if(ix==0){coffee=new CheckBox(this);coffee.setText("咖啡");coffee.setTextSize(14);coffee.setChecked(p.getBoolean(key("breakfast_coffee"),false));coffee.setOnCheckedChangeListener((v,c)->{p.edit().putBoolean(key("breakfast_coffee"),c).apply();});b.addView(coffee);}
 LinearLayout tr=row();tr.addView(t("进食时间",14,true,INK),new LinearLayout.LayoutParams(0,-2,1));Button tb=btn(timeText(k),Color.WHITE,INK);tb.setOnClickListener(v->timeDialog(k,tb));tr.addView(tb,new LinearLayout.LayoutParams(dp(120),dp(46)));b.addView(sp(7));b.addView(tr);Button confirm=btn(p.getBoolean(key(k+"_confirmed"),false)?"已确认本餐 · 点此修改":"确认本餐",LIME,INK);confirm.setOnClickListener(v->{boolean old=p.getBoolean(key(k+"_confirmed"),false);p.edit().putBoolean(key(k+"_confirmed"),!old).apply();saveDailySnapshot();render();});b.addView(sp(7));b.addView(confirm,new LinearLayout.LayoutParams(-1,dp(46)));total.setText("本餐 "+Math.round(mealKcal(ix))+" kcal");return card(b,Color.WHITE);}
 int indexOf(EditText e,EditText[] arr){for(int i=0;i<arr.length;i++)if(arr[i]==e)return i;return 0;}
 void timeDialog(String k,Button target){int h=p.getInt(key(k+"_hour"),-1),m=p.getInt(key(k+"_minute"),-1);LocalTime now=LocalTime.now();if(h<0){h=now.getHour();m=now.getMinute();}TimePickerDialog dlg=new TimePickerDialog(this,(v,hh,mm)->{p.edit().putInt(key(k+"_hour"),hh).putInt(key(k+"_minute"),mm).apply();target.setText(String.format(Locale.CHINA,"%02d:%02d",hh,mm));updateAll();},h,m,true);dlg.show();}
 String timeText(String k){int h=p.getInt(key(k+"_hour"),-1),m=p.getInt(key(k+"_minute"),-1);return h<0?"设置 XX:XX":String.format(Locale.CHINA,"%02d:%02d",h,m);}
 View waterCard(){LinearLayout b=col();waterV=t("今日 0 / 2000 ml",20,true,INK);b.addView(waterV);b.addView(sp(8));LinearLayout buttons=row();for(int x:new int[]{250,500}){Button q=btn("+"+x+" ml",LIME,INK);q.setOnClickListener(v->{int cur=p.getInt(key("water_ml"),0)+x;p.edit().putInt(key("water_ml"),cur).apply();updateAll();});buttons.addView(q,new LinearLayout.LayoutParams(0,dp(46),1));}b.addView(buttons);b.addView(sp(8));EditText custom=num("直接输入今日总饮水 ml");custom.setText(p.getInt(key("water_ml"),0)==0?"":String.valueOf(p.getInt(key("water_ml"),0)));custom.setOnFocusChangeListener((v,has)->{if(!has){int ml=iv(custom);p.edit().putInt(key("water_ml"),ml).apply();updateAll();}});b.addView(custom,new LinearLayout.LayoutParams(-1,dp(48)));return card(b,Color.WHITE);}
 View trendSection(String title,String metric){LinearLayout b=col();List<TrendChartView.Point> data=trendData(metric);float avg=0;for(TrendChartView.Point x:data)avg+=x.value;if(!data.isEmpty())avg/=data.size();b.addView(t(title+(data.isEmpty()?"":"  · 近7次平均 "+Math.round(avg)+(metric.equals("weight")?"":"%")),15,true,INK));TrendChartView chart=new TrendChartView(this);chart.setData(data);chart.setOnPointClickListener(pt->new AlertDialog.Builder(this).setTitle(pt.label+" · "+title).setMessage(pt.detail).setPositiveButton("知道了",null).show());b.addView(chart,new LinearLayout.LayoutParams(-1,dp(190)));return card(b,Color.WHITE);}
 List<TrendChartView.Point> trendData(String metric){List<TrendChartView.Point> out=new ArrayList<>();String raw=p.getString("daily_snapshots","");if(metric.equals("weight")){String h=p.getString("history","");String[] lines=h.split(";");for(int i=Math.max(0,lines.length-7);i<lines.length;i++){String[] q=lines[i].split(",");if(q.length==2)try{float kg=Float.parseFloat(q[1]);float display=Math.max(0,Math.min(100,100-(kg-TARGET)*10));out.add(new TrendChartView.Point(q[0].substring(5),display,"体重："+q[1]+" kg\n距离64KG："+trim(Math.max(0,kg-TARGET))+" kg"));}catch(Exception ignored){}}return out;}String[] lines=raw.split(";");for(int i=Math.max(0,lines.length-7);i<lines.length;i++){String[] q=lines[i].split("\\|");if(q.length<9)continue;try{int pos=metric.equals("diet_stability")?1:metric.equals("diet_health")?2:metric.equals("sleep_stability")?3:metric.equals("sleep_health")?4:metric.equals("exercise_stability")?5:metric.equals("exercise_health")?6:7;float v=Float.parseFloat(q[pos]);out.add(new TrendChartView.Point(q[0].substring(5),v,q[8]));}catch(Exception ignored){}}return out;}
 void saveDailySnapshot(){int[] scores=scores();String detail="睡眠："+sleepMinutes()/60+"小时"+sleepMinutes()%60+"分钟\n16+8稳定率："+scores[0]+"%\n饮食健康率："+scores[1]+"%\n睡眠稳定率："+scores[2]+"%\n睡眠健康率："+scores[3]+"%\n运动稳定率："+scores[4]+"%\n运动健康率："+scores[5]+"%\n喝水完成率："+scores[6]+"%\n摄入："+Math.round(mealKcalAll())+" kcal\n饮水："+p.getInt(key("water_ml"),0)+" ml";String today=LocalDate.now().toString(),entry=today+"|"+scores[0]+"|"+scores[1]+"|"+scores[2]+"|"+scores[3]+"|"+scores[4]+"|"+scores[5]+"|"+scores[6]+"|"+detail.replace("|","/").replace(";","，");List<String> keep=new ArrayList<>();for(String x:p.getString("daily_snapshots","").split(";"))if(!x.isEmpty()&&!x.startsWith(today+"|"))keep.add(x);keep.add(entry);p.edit().putString("daily_snapshots",String.join(";",keep)).apply();}
 int[] scores(){int first=-1,last=-1;for(String k:mealKeys){int h=p.getInt(key(k+"_hour"),-1),m=p.getInt(key(k+"_minute"),-1);if(h>=0){int x=h*60+m;if(first<0)first=x;last=x;}}int dietStable=HealthScorer.fastingWindowScore(first,last);float[] vals=new float[16];for(int i=0;i<4;i++)for(int j=0;j<4;j++)vals[i*4+j]=fv(meal[i][j]);int dietHealth=HealthScorer.dietHealth(vals),sleepHealth=HealthScorer.sleepHealth(sleepMinutes()),sleepStable=100;int target=activityTarget(),actual=actualKcal();int exStable=HealthScorer.exerciseStability(actual,target),exHealth=HealthScorer.exerciseHealth(actual,target),water=HealthScorer.waterCompletion(p.getInt(key("water_ml"),0),2000);return new int[]{dietStable,dietHealth,sleepStable,sleepHealth,exStable,exHealth,water};}
 void updateSleep(){if(sleepDur==null||sh==null)return;int m=sleepMinutes();boolean locked=p.getBoolean(key("sleep_confirmed"),false);sleepDur.setText("共 "+m/60+" 小时 "+m%60+" 分钟"+(locked?"  ✓ 已确认":"  · 点此确认"));p.edit().putInt(key("sleep_total_minutes"),m).apply();}
 int sleepMinutes(){if(sh==null)return p.getInt(key("sleep_total_minutes"),0);int s=sh.getValue()*60+sm.getValue(),e=wh.getValue()*60+wm.getValue(),d=e-s;if(d<0)d+=1440;return d;}
 void updateAll(){if(intakeV==null)return;int intake=Math.round(mealKcalAll());intakeV.setText("今日摄入估算："+intake+" kcal");int first=-1,last=-1;for(String k:mealKeys){int h=p.getInt(key(k+"_hour"),-1),m=p.getInt(key(k+"_minute"),-1);if(h>=0){int x=h*60+m;if(first<0)first=x;last=x;}}if(first>=0&&last>=0){int span=last-first;if(span<0)span+=1440;fastingV.setText("16+8：进食窗口 "+span/60+"小时"+span%60+"分钟 · "+(span<=480?"符合":"超过8小时"));}else fastingV.setText("16+8：设置每餐进食时间后自动判断");int water=p.getInt(key("water_ml"),0);waterV.setText("今日 "+water+" / 2000 ml · "+HealthScorer.waterCompletion(water,2000)+"%");updatePlan();}
 int activityTarget(){float sleep=sleepMinutes()/60f;return ActivityPlanner.suggestedActivityKcal(Math.round(mealKcalAll()),sleep);}int actualKcal(){float w=p.getFloat("weight",0);if(w<=0)return 0;return ActivityPlanner.metCalories(6f,w,iv(ball))+ActivityPlanner.briskWalkCalories(w,iv(walk))+ActivityPlanner.runningCalories(w,fv(run));}
 void updatePlan(){if(planV==null||actualV==null)return;float w=p.getFloat("weight",0);if(w<=0){planV.setText("先记录体重后，再换算打球时长、快走步数和跑步圈数。");actualV.setText("记录体重后再计算运动消耗。");return;}int target=activityTarget(),bm=ActivityPlanner.basketballMinutesFor(target,w),steps=ActivityPlanner.briskWalkStepsFor(target,w);float laps=ActivityPlanner.runningLapsFor(target,w);planV.setText("建议活动目标：约 "+target+" kcal\n≈ 打球 "+fmtMin(bm)+"\n≈ 快走 "+steps+" 步\n≈ 跑步 "+one(laps)+" 圈（400m/圈）");int actual=actualKcal();actualV.setText("实际运动消耗估算："+actual+" kcal\n"+(actual>=target?"已达到今天建议活动目标":"距离建议活动目标还差约 "+(target-actual)+" kcal"));}
 float mealKcal(int i){if(meal[i][0]==null)return 0;return fv(meal[i][0])*180+fv(meal[i][1])*160+fv(meal[i][2])*50+fv(meal[i][3])*220;}float mealKcalAll(){float s=0;for(int i=0;i<4;i++)s+=mealKcal(i);return s;}
 void watch(EditText e,String k){e.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int b,int c){}public void onTextChanged(CharSequence s,int a,int b,int c){}public void afterTextChanged(Editable s){if(rendering)return;p.edit().putString(key(k),s.toString().trim()).apply();updateAll();}});}
 void saveWeight(EditText e){String r=e.getText().toString().trim();if(r.isEmpty()){toast("先输入今天的体重");return;}float v;try{v=Float.parseFloat(r);}catch(Exception x){toast("体重格式不对");return;}if(v<35||v>200){toast("请确认体重数值");return;}String td=LocalDate.now().toString();List<String> keep=new ArrayList<>();for(String line:p.getString("history","").split(";"))if(!line.isEmpty()&&!line.startsWith(td+","))keep.add(line);keep.add(td+","+v);p.edit().putFloat("weight",v).putString("history",String.join(";",keep)).apply();e.setText("");saveDailySnapshot();refresh();updateAll();toast("已记录 "+trim(v)+" kg");}
 void toggleLiquid(){String td=LocalDate.now().toString();List<String>d=liquidDates();if(d.contains(td))d.remove(td);else if(weekCount(d)>=2){toast("本周已经安排2次液断");return;}else d.add(td);p.edit().putString("liquid_dates",String.join(",",d)).apply();render();}List<String> liquidDates(){List<String>o=new ArrayList<>();for(String s:p.getString("liquid_dates","").split(","))if(!s.isEmpty())o.add(s);return o;}int weekCount(List<String>d){int c=0;WeekFields wf=WeekFields.of(Locale.CHINA);LocalDate n=LocalDate.now();for(String s:d)try{LocalDate x=LocalDate.parse(s);if(x.get(wf.weekOfWeekBasedYear())==n.get(wf.weekOfWeekBasedYear())&&x.get(wf.weekBasedYear())==n.get(wf.weekBasedYear()))c++;}catch(Exception ignored){}return c;}boolean isLiquid(){return liquidDates().contains(LocalDate.now().toString());}
 void refresh(){float w=p.getFloat("weight",0);gapV.setText(w==0?"--":trim(Math.max(0,w-TARGET)));daysV.setText(String.valueOf(Math.max(0,ChronoUnit.DAYS.between(LocalDate.now(),GOAL))));weightV.setText(w==0?"-- kg":trim(w)+" kg");liquidV.setText("剩 "+Math.max(0,2-weekCount(liquidDates()))+" 次");}
 String pref(String k){return p.getString(key(k),"");}String key(String k){return k+"_"+LocalDate.now();}int iv(EditText e){try{return Integer.parseInt(e.getText().toString().trim());}catch(Exception x){return 0;}}float fv(EditText e){try{return Float.parseFloat(e.getText().toString().trim());}catch(Exception x){return 0;}}String fmtMin(int m){return m<60?m+" 分钟":m/60+" 小时"+(m%60==0?"":" "+m%60+" 分钟");}String one(float v){return String.format(Locale.CHINA,"%.1f",v);}String trim(float v){return v==(long)v?String.valueOf((long)v):String.format(Locale.CHINA,"%.1f",v);}
 LinearLayout heroStat(String l,String v,String u){LinearLayout b=col();b.setGravity(Gravity.CENTER);b.addView(t(l,13,true,Color.rgb(195,198,188)));LinearLayout ln=row();ln.setGravity(Gravity.CENTER);TextView x=t(v,48,true,Color.WHITE);ln.addView(x);TextView uu=t(u,14,true,LIME);LinearLayout.LayoutParams up=new LinearLayout.LayoutParams(-2,-2);up.setMargins(dp(7),dp(19),0,0);ln.addView(uu,up);b.addView(ln);return b;}TextView mini(LinearLayout par,String l,String v){LinearLayout b=col();b.setGravity(Gravity.CENTER);b.addView(t(l,11,false,MUTED));TextView x=t(v,16,true,INK);b.addView(x);par.addView(b,new LinearLayout.LayoutParams(0,dp(78),1));return x;}void section(String a,String b){root.addView(sp(22));root.addView(t(a,21,true,INK));root.addView(sp(3));root.addView(t(b,13,false,MUTED));root.addView(sp(10));}LinearLayout row(){LinearLayout v=new LinearLayout(this);v.setOrientation(LinearLayout.HORIZONTAL);v.setGravity(Gravity.CENTER_VERTICAL);return v;}LinearLayout col(){LinearLayout v=new LinearLayout(this);v.setOrientation(LinearLayout.VERTICAL);return v;}TextView t(String s,int z,boolean bold,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);if(bold)v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return v;}EditText dec(String h){return input(h,InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);}EditText num(String h){return input(h,InputType.TYPE_CLASS_NUMBER);}EditText input(String h,int type){EditText e=new EditText(this);e.setHint(h);e.setTextSize(14);e.setInputType(type);e.setSingleLine();e.setPadding(dp(15),0,dp(15),0);e.setBackground(round(Color.WHITE));return e;}Button btn(String s,int bg,int fg){Button b=new Button(this);b.setText(s);b.setTextColor(fg);b.setTextSize(13);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setAllCaps(false);b.setBackground(round(bg));return b;}View card(View v,int c){LinearLayout x=col();x.setPadding(dp(14),dp(12),dp(14),dp(12));x.setBackground(round(c));x.addView(v,new LinearLayout.LayoutParams(-1,-2));return x;}GradientDrawable round(int c){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(15));return g;}View sp(int h){View v=new View(this);v.setLayoutParams(new LinearLayout.LayoutParams(1,dp(h)));return v;}int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
}
